version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    env_file:
      - ./backend/.env
    # environment:
    # - DEBUG=1
    # - DB_NAME=myapp
    # - DB_USER=postgres
    # - DB_PASSWORD=postgres
    # - DB_HOST=db
    # - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:
  backend_media:

networks:
  app-network:
    driver: bridge
